name: "devsecops tools"

on: 
    push: 
        branches: [develop]

jobs:
    sast-codeql:
        runs-on: ubuntu-latest
        steps:
        #- uses: actions/checkout@v6
        - name: listar archivos
          run: ls
